// Generated by Wrangler by running `wrangler types`

interface Env {
	KOFI_VERIFICATION_TOKEN: string;
	DISCORD_WEBHOOK_URL: string;
	DISCORD_WEBHOOK_DISPLAY_NAME: string;
	DISCORD_WEBHOOK_AVATAR_URL: string;
}
